- hosts: all
  sudo:	True
  user:	vagrant
  tasks:

    - name: "Atualizando pacotes"
      shell: sudo apt-get -y update
    - name: Install MySQL
      apt:
        name: "{{ item }}"
      with_items:
        - mysql-server

    - name: "Criando o arquivo de configuração allow_external.cnf"
      shell: sudo cp /vagrant/allow_external.cnf /etc/mysql/conf.d/allow_external.cnf

    - name: "Reiniciando o Mysql"
      shell: sudo service mysql restart

    - name: "Criando o banco loja_schema"
      shell: sudo mysqladmin -u root -p create loja_schema

    - name: "Removendo usuario padrão"
      shell: sudo mysql -uroot -p -e "DELETE FROM mysql.user WHERE user='\>'; FLUSH PRIVILEGES"

    - name: "Criando novo usuario"
      shell: mysql -uroot -p -e "GRANT ALL PRIVILEGES ON loja_schema.* TO 'loja'@'%' IDENTIFIED BY 'lojasecret';"


