- hosts: all
  sudo:	True
  user:	vagrant
  tasks:
    - name: "Atualizando pacotes"
      shell: sudo apt-get -y update

    - name: "Instalando tomcat7 mysql-client "
      shell: sudo apt-get install -y tomcat7 mysql-client

    - name: "Configurando o Keytool para conexões ssl"
      shell: sudo keytool -genkey -alias tomcat -keyalg RSA -keystore /var/lib/tomcat7/conf/.keystore < /vagrant/tmp

    - name: "Removendo /var/lib/tomcat7/conf/server.xml"   ## ok
      shell: sudo rm /var/lib/tomcat7/conf/server.xml

    - name: "Copiando /var/lib/tomcat7/conf/server.xml correto" 
      shell: sudo cp /vagrant/server.xml /var/lib/tomcat7/conf/server.xml  ## ok

    - name: "Removendo /etc/default/tomcat7"    ## ok
      shell: sudo rm /etc/default/tomcat7

    - name: "Copiando /etc/default/tomcat7 atualizado"
      shell: sudo cp /vagrant/tomcat7 /etc/default/tomcat7  ## ok

    - name: "Reiniciando tomcat"   ## ok
      shell: sudo service tomcat7 restart

    - name: "Instalando git, maven2 e openjdk-6-jdk"    ## ok
      shell: sudo apt-get install -y git maven2 openjdk-6-jdk

    - name: "Clonando o projeto loja-virtual-devops.git"   ## ok
      shell: git clone https://github.com/dtsato/loja-virtual-devops.git
    
    - name: "Export MAVEN_OPTS"   
      shell: export MAVEN_OPTS=-Xmx256m            ##########

    - name: "Copiando o arquivo de configuração do Maven"
      shell: sudo cp /vagrant/pom.xml /home/vagrant/pom.xml

    - name: "Buinging"
      shell: sudo mvn install 

    - name: "Removendo /var/lib/tomcat7/conf/context.xml"
      shell: sudo rm /var/lib/tomcat7/conf/context.xml

    - name: "Copiando /var/lib/tomcat7/conf/context.xml correto" 
      shell: sudo cp /vagrant/context.xml /var/lib/tomcat7/conf/context.xml

    - name: "Deploy"
      shell: sudo cp /home/vagrant/loja-virtual-devops/site/target/devopsnapratica.war /var/lib/tomcat7/webapps

    - name: "Reiniciando o tomcat7"
      shell: sudo service tomcat7 restart




    




    


